// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyryutLp_aUVs-GJkmtzuXXVSfdCBBbUE',
    appId: '1:518410047825:web:d2a4f4f5fb031445818370',
    messagingSenderId: '518410047825',
    projectId: 'teste-ad230',
    authDomain: 'teste-ad230.firebaseapp.com',
    databaseURL: 'https://teste-ad230-default-rtdb.firebaseio.com',
    storageBucket: 'teste-ad230.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa9OUC7NdqDBFn2CjSo8Q3xYGfGZ6IMak',
    appId: '1:518410047825:android:d01baf4987afcd75818370',
    messagingSenderId: '518410047825',
    projectId: 'teste-ad230',
    databaseURL: 'https://teste-ad230-default-rtdb.firebaseio.com',
    storageBucket: 'teste-ad230.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYMeQyvhsNIKOUZqBt7J7pPJp-j5dHJng',
    appId: '1:518410047825:ios:65e468ee5bbcc8ab818370',
    messagingSenderId: '518410047825',
    projectId: 'teste-ad230',
    databaseURL: 'https://teste-ad230-default-rtdb.firebaseio.com',
    storageBucket: 'teste-ad230.appspot.com',
    iosClientId: '518410047825-aqt7e455fijms7rvkmbrq018g2ijlf6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYMeQyvhsNIKOUZqBt7J7pPJp-j5dHJng',
    appId: '1:518410047825:ios:65e468ee5bbcc8ab818370',
    messagingSenderId: '518410047825',
    projectId: 'teste-ad230',
    databaseURL: 'https://teste-ad230-default-rtdb.firebaseio.com',
    storageBucket: 'teste-ad230.appspot.com',
    iosClientId: '518410047825-aqt7e455fijms7rvkmbrq018g2ijlf6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicacao',
  );
}
